### ISSUE TITLE
Support for Run

### ISSUE THREAD

**Issue by Goffen** [btford/ngmin#46]
It does not minify-safeguard ("module").run(function(inject) {});

**Comment by oltodo** [comment]
:+1:

**Comment by raine** [comment]
:+1:

**Comment by ghost** [comment]
We are experiencing this issue.  We found that if run is the only method call or by moving run to the top as the first method call, there is no issue.  When run follows another method call, then this issue is present.

**Issue:**  
- angular.module(...).config(...).run(...)

**No Issue:**
- angular.module(...).run(...)
- angular.module(...).run(...).config(...)

**Comment by mrwillis21** [comment]
:+1: Seeing this as well.

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
