### ISSUE TITLE
The future of ngmin

### ISSUE THREAD

**Issue by mlegenhausen** [btford/ngmin#70]
I am a little bit worried about ngmin and the further support of the project cause in the last 3 months the only accepted push requests where for readme updates. Getting feedback from @btford for push requests are even more rare.

So what are the plans for the project? Is it time to fork ngmin or is it possible to add more maintainers for the project?

**Comment by btford** [comment]
Malte,

Thanks for your concern. I've been working on a rewrite of ngmin to address
some of the broader concerns of existing users that can't be addressed
otherwise. This is taking longer that I'd hoped, but I'm still making
progress.

I'd be happy to add more contributors.

-Brian

On Thu, Jan 16, 2014 at 3:24 AM, Malte Legenhausen <notifications@github.com

**Comment by mlegenhausen** [comment]
Thanks for your fast reply that sounds good and give hope. It is possible to get some insights in your rewrite? Will it be the same tool as it is yet or are you planing something like your `DI` annotation from issue #44?

Maybe I can help you out with pull request to complete the list of standard annotations for the angular core modules until your rewrite is ready?

**Comment by btford** [comment]
@mlegenhausen it will be the same tool.

The problem is that it's impossible to construct a finite list for annotations via static analysis.

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
